modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/cookiejarmods/bageling/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

logoFile = "logo.png"

authors="${mod_authors}"

description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId ="farmersdelight"
type="optional"
reason="Salmon Bagel and Bagel Dough"
versionRange="[1.2.9,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId ="neapolitan"
type="optional"
reason="Strawberry Jam Bagel"
versionRange="[6.0.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId ="create"
type="optional"
reason="Bagel Dough"
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId ="brewinandchewin"
type="optional"
reason="Cheese Recipes"
versionRange="[4.4.1,)"
ordering="AFTER"
side="BOTH"
